### ISSUE TITLE
What is Admin UI be built in?

### ISSUE THREAD

**Issue by nevil2** [nemphi/hanabicms#1]
I'm interested in an Edge-Function CMS.

Is anyone else making one?

Do you want to talk?

Nevil
info.topoeditor@gmail.com

**Comment by shixzie** [comment]
Hi! Sorry for not answering, I got really busy and forgot I had started this.

To answer the question, I'm planning to build the Admin UI with [HTMX](https://htmx.org) to be able to co-host the cms admin panel within any kind of codebase.

Those two CMS's are great! Honestly I didn't know they existed but right now I think they don't support end-to-end type safety (I might be wrong though). 

I'm building a developer-first, code configurable CMS (inspiration taken from [Payload](https://payloadcms.com/)), basically declare your schema/collections in code and then you manage the data via the Admin UI.

I'll be working on this for a while now that I have some time, expect some awesome stuff _soon TM_.
